apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pathservice
  template:
    metadata:
      labels:
        app: pathservice
    spec:
      containers:
      - name: pathservice
        image: quay.io/instructlab-ui/pathservice:<IMAGE_TAG>
        ports:
        - containerPort: 4000
          hostPort: 4000
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doclingserve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doclingserve
  template:
    metadata:
      labels:
        app: doclingserve
    spec:
      containers:
      - name: doclingserve
        image: quay.io/ds4sd/docling-serve:<IMAGE_TAG>
        ports:
        - containerPort: 5001
          hostPort: 5001
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: quay.io/instructlab-ui/ui:<IMAGE_TAG>
        securityContext:
          runAsGroup: 1000
        volumeMounts:
        - name: taxonomy-repo
          mountPath: /tmp/.instructlab-ui
        env:
        - name: IL_UI_DEPLOYMENT
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_UI_DEPLOYMENT
        - name: IL_UI_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_UI_ADMIN_USERNAME
        - name: IL_UI_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_UI_ADMIN_PASSWORD
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXTAUTH_SECRET
        - name: NEXTAUTH_URL
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXTAUTH_URL
        - name: NEXT_PUBLIC_TAXONOMY_ROOT_DIR
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_TAXONOMY_ROOT_DIR
        - name: NEXT_PUBLIC_EXPERIMENTAL_FEATURES
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_EXPERIMENTAL_FEATURES
        - name: IL_ENABLE_DEV_MODE
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: IL_ENABLE_DEV_MODE
        - name: NEXT_PUBLIC_API_SERVER
          valueFrom:
            secretKeyRef:
              name: ui-env
              key: NEXT_PUBLIC_API_SERVER
        ports:
        - containerPort: 3000
          hostPort: 3000
        imagePullPolicy: Always
      volumes:
      - name: taxonomy-repo
        hostPath:
          path: <TAXONOMY_ROOT_DIR>
          type: Directory
